# Generated by Django 4.0.4 on 2022-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='reports',
            field=models.TextField(default='[]'),
        ),
    ]
